# Generated by Django 3.2 on 2021-04-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='user.Task'),
        ),
    ]
